//auth
export const USUARIO_REGISTRADO_EXITO = 'USUARIO_REGISTRADO_EXITO';
export const USUARIO_REGISTRADO_ERROR = 'USUARIO_REGISTRADO_ERROR';

export const LOGIN_EXITO = 'LOGIN_EXITO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';

export const CERRAR_SESION = 'CERRAR_SESION';

export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

//app
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';

export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS';




 