export const USUARIO_REGISTRADO_EXITO = 'USUARIO_REGISTRADO_EXITO';
export const USUARIO_REGISTRADO_ERROR = 'USUARIO_REGISTRADO_ERROR';

export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const LOGIN_EXITO = 'LOGIN_EXITO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';

export const CERRAR_SESION = 'CERRAR_SESION';


 